// Code generated by candi v1.18.0.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	datamanagementusecase "zania-api/internal/modules/data-management/usecase"
	"zania-api/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		DataManagement() datamanagementusecase.DataManagementUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		datamanagementusecase.DataManagementUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.DataManagementUsecase, setSharedUsecaseFunc = datamanagementusecase.NewDataManagementUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) DataManagement() datamanagementusecase.DataManagementUsecase {
	return uc.DataManagementUsecase
}
