// Code generated by candi v1.18.0.

package repository

import (
	"context"
	"database/sql"
	"fmt"

	datamanagementrepo "zania-api/internal/modules/data-management/repository"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"zania-api/pkg/shared"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type (
	RepoSQL interface {
		WithTransaction(ctx context.Context, txFunc func(ctx context.Context) error) (err error)

		DataManagementRepo() datamanagementrepo.DataManagementRepository
	}

	repoSQLImpl struct {
		readDB, writeDB *gorm.DB

		datamanagementRepo datamanagementrepo.DataManagementRepository
	}
)

var (
	globalRepoSQL RepoSQL
)

func setSharedRepoSQL(readDB, writeDB *sql.DB) {
	gormRead, err := gorm.Open(postgres.New(postgres.Config{
		Conn: readDB,
	}), &gorm.Config{})
	if err != nil {
		panic(err)
	}

	gormWrite, err := gorm.Open(postgres.New(postgres.Config{
		Conn: writeDB,
	}), &gorm.Config{SkipDefaultTransaction: true})
	if err != nil {
		panic(err)
	}

	shared.AddGormCallbacks(gormRead)
	shared.AddGormCallbacks(gormWrite)

	globalRepoSQL = NewRepositorySQL(gormRead, gormWrite)
}

func GetSharedRepoSQL() RepoSQL {
	return globalRepoSQL
}

func NewRepositorySQL(readDB, writeDB *gorm.DB) RepoSQL {

	return &repoSQLImpl{
		readDB: readDB, writeDB: writeDB,

		datamanagementRepo: datamanagementrepo.NewDataManagementRepoSQL(readDB, writeDB),
	}
}

func (r *repoSQLImpl) WithTransaction(ctx context.Context, txFunc func(ctx context.Context) error) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "RepoSQL:Transaction")
	defer trace.Finish()

	tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB)
	if !ok {
		tx = r.writeDB.Begin()
		if tx.Error != nil {
			return tx.Error
		}

		defer func() {
			if err != nil {
				tx.Rollback()
				trace.SetError(err)
			} else {
				tx.Commit()
			}
		}()
		ctx = candishared.SetToContext(ctx, candishared.ContextKeySQLTransaction, tx)
	}

	errChan := make(chan error)
	go func(ctx context.Context) {
		defer func() {
			if r := recover(); r != nil {
				errChan <- fmt.Errorf("panic: %v", r)
			}
			close(errChan)
		}()

		if err := txFunc(ctx); err != nil {
			errChan <- err
		}
	}(ctx)

	select {
	case <-ctx.Done():
		return fmt.Errorf("canceled or timeout: %v", ctx.Err())
	case e := <-errChan:
		return e
	}
}

func (r *repoSQLImpl) DataManagementRepo() datamanagementrepo.DataManagementRepository {
	return r.datamanagementRepo
}
